version: '3.9'

services:
  web:
    build: .
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=rasadb
      - MYSQL_ROOT_USER=root
    depends_on:
      - db
  db:
    image: mysql:latest
    volumes:
      - /data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=rasadb
      - MYSQL_ROOT_USER=root
    ports:
      - "3307:3306"
    expose:
      - 3307
